- resources/views/index.blade.php
> index.blade.php

- resources/views/register.blade.php
> added register page

- app/Http/Controllers/ForgotPassword.php
- resources/views/forgot.blade.php
- routes/web.php
> forgot password page

- app/Http/Controllers/Pages.php
- public/JS/main.js
- resources/views/forgot.blade.php
- resources/views/login.blade.php
- resources/views/reset_password.blade.php
- routes/web.php
paglipat lipat ng pages of login, forgot password, and reset password
> Pages (Controller)

- app/Http/Controllers/Pages.php
- resources/views/employees/approval.blade.php
- resources/views/employees/document_request.blade.php
- routes/web.php
- FIxed the Routing of the File button in Document_Request Page
- Added Front End for the Approval Page
> Added Approval Page

- resources/views/admin/announcement.blade.php
- resources/views/admin/calendar.blade.php
- resources/views/admin/document_request.blade.php
- resources/views/admin/privileges.blade.php
- resources/views/admin/time_record.blade.php
- resources/views/admin/userinfo.blade.php
> Added Admin Pages

- app/Http/Controllers/Pages.php
- resources/views/admin/tr_deped.blade.php
- resources/views/admin/tr_student.blade.php
- routes/web.php
-Routing for additional TIme Record pages for admin
> Added Routing

- resources/views/admin/calendar.blade.php
> Calendar Front-end

- app/Http/Controllers/Pages.php
- resources/views/admin/time_record.blade.php
- resources/views/admin/tr_deped.blade.php
- resources/views/admin/tr_employee.blade.php
- resources/views/admin/tr_student.blade.php
-Design for Time Record (Admin)
-Added routing for the tr_student, tr_employee, and tr_deped
> Added admin Time Record Front End

- resources/views/admin/tr_employee.blade.php
> tr_employee.blade.php

- app/Http/Controllers/Pages.php
- public/CSS/student.css
- resources/views/component/employee/annoucement_component.blade.php
- resources/views/component/student/announcement_component.blade.php
- resources/views/employees/announcement.blade.php
- resources/views/employees/view-announcement.blade.php
- resources/views/student/home.blade.php
- resources/views/student/view-announcement.blade.php
- routes/web.php
-Added announcement view page for Student and Employee portal
> Announcement View Page

- public/CSS/student.css
- resources/views/employees/userinfo.blade.php
- resources/views/student/home.blade.php
> Completed User Info

- resources/views/admin/student_masterlist.blade.php
- routes/web.php
> Student Masterlis Forms 2.0

- app/Http/Controllers/EmployeeMasterListController.php
- resources/views/admin/employee_masterlist.blade.php
- routes/web.php
> Employee Incomplete

- app/Http/Controllers/ForgotPassword.php
- app/Http/Controllers/Pages.php
- app/Http/Controllers/StudentMasterlistController.php
- app/Models/Students.php
- database/migrations/2024_02_01_060442_create_students_table.php
- database/seeders/DatabaseSeeder.php
- public/JS/addStudent.js
- resources/views/admin/student_masterlist.blade.php
- routes/web.php
- Add student button now successfully adds the student into the database
- Table view in the Student Master List's page now reflects the students that is registered in the database
> Student Master List Add Student Feature

- public/CSS/admin.css
- resources/views/admin/employee_masterlist.blade.php
- resources/views/admin/student_masterlist.blade.php
- resources/views/admin/time_record.blade.php
- resources/views/component/admin/emp_masterlist_component.blade.php
employee masterlist- sort functions , 
student masterlist- forms and search bar
time-record - interactive size
> all masterlist 

- app/Http/Controllers/EmployeeMasterListController.php
- app/Http/Controllers/Pages.php
- app/Models/Employees.php
- database/factories/EmployeesFactory.php
- database/migrations/2024_01_29_022054_create_employees_table.php
- resources/views/admin/employee_masterlist.blade.php
- resources/views/component/admin/emp_masterlist_component.blade.php
Finished the Add employee function
> Back end for Employee Masterlist

- resources/views/admin/employee_masterlist.blade.php
- resources/views/admin/student_masterlist.blade.php
sorting button for student masterlist
add button employee for employee masterlist
> student and employee masterlist

- app/Http/Controllers/EmployeeMasterListController.php
- app/Models/Employees.php
- database/factories/EmployeesFactory.php
- database/migrations/2024_01_29_022054_create_employees_table.php
- public/CSS/admin.css
- resources/views/admin/employee_masterlist.blade.php
- resources/views/component/admin/emp_masterlist_component.blade.php
- routes/web.php
Finished all of the Employee Masterlist Functionalities
> Employee Masterlist

- app/Http/Controllers/GradeLevelandSectionController.php
- app/Http/Controllers/StudentMasterlistController.php
- app/Models/GradeLevelandSection.php
- app/Models/Students.php
- database/migrations/2024_02_01_060442_create_students_table.php
- database/migrations/2024_02_26_052055_create_grade_level_and_sections_table.php
- public/CSS/admin.css
- public/CSS/studentMasterlist.css
- public/JS/Admin/addGradeSection.js
- public/JS/Admin/addStudent.js
- public/JS/Admin/studentMasterlist.js
- resources/views/admin/student_masterlist.blade.php
- routes/web.php
- Add Student Feature
- Add Grade level & Section Feature
- Remove Grade level & Section Feature
- Filter Feature for the table
- Action Button Feature
- Status Update Feature
- Student Details Update Feature
- Student Grade level & Section Update Feature
> Student Master list Full Stack

- app/Http/Controllers/CheckInOutController.php
- app/Http/Controllers/Pages.php
- app/Models/Calendar.php
- app/Models/EmployeeLogs.php
- app/Models/StudentLogs.php
- database/migrations/2024_03_07_035301_create_student_logs_table.php
- database/migrations/2024_03_07_035318_create_employee_logs_table.php
- public/CSS/scanner.css
- resources/views/admin/announcement.blade.php
- resources/views/admin/dashboard.blade.php
- resources/views/admin/tr_student.blade.php
- resources/views/component/student/sidenav.blade.php
- resources/views/qr.blade.php
- resources/views/student/calendar.blade.php
- resources/views/student/home.blade.php
- resources/views/student/user.blade.php
- routes/web.php
-inclusion of qr scanner
-dashboard
-calendar
> New changes on the admin panel

- app/Http/Controllers/EmployeeMasterListController.php
- app/Http/Controllers/Pages.php
- app/Http/Controllers/StudentMasterlistController.php
- resources/views/student/calendar.blade.php
-Fixed Pages for Student's Portal (Home, User Info, Calendar)
-Employee and Student Master List removed the Auth::guard initialization
> Changes based on the System's Drip Check

- public/CSS/style.css
- resources/views/login.blade.php
Made Some UI changes:
Font weight of h1 is changed
Redundant BG image removed
> Login Page - Front End Update

- app/Http/Controllers/AAnnouncementsController.php
- app/Http/Controllers/Pages.php
- public/CSS/student.css
- resources/views/admin/announcement.blade.php
- resources/views/component/employee/annoucement_component.blade.php
- resources/views/component/student/announcement_component.blade.php
- resources/views/employees/announcement.blade.php
- resources/views/employees/view-announcement.blade.php
- resources/views/student/announcement.blade.php
- resources/views/student/view-announcement.blade.php
- routes/web.php
Connected student and employee announcement pages to database.
to add (pag kaya ang hirap e haha): students and employee have separate announcement views. for now all announcements made are viewable for everyone
> Student And Employee Announcements synced

- app/Http/Controllers/AAnnouncementsController.php
- app/Models/AAnnouncements.php
- database/migrations/2024_02_27_061324_create_a_announcements_table.php
- resources/views/admin/announcement.blade.php
- resources/views/student/view-announcement.blade.php
Recipient of announcement is implemented:
*Admin can now send announcements on students/employee specifically. In example, if an admin posts an announcement for employees students would not be able to view/see it. vice versa happens for students
> Announcement Pages Finished 
